# Copyright (c) 2025 CoReason, Inc.
#
# This software is proprietary and dual-licensed.
# Licensed under the Prosperity Public License 3.0 (the "License").
# A copy of the license is available at https://prosperitylicense.com/versions/3.0.0
# For details, see the LICENSE file.
# Commercial use beyond a 30-day trial requires a separate license.
#
# Source Code: https://github.com/CoReason-AI/coreason_episteme

"""
Data models for the coreason-episteme application.

This module defines the Pydantic models used for representing hypotheses,
knowledge gaps, critiques, and provenance traces.
"""

import uuid
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ConfidenceLevel(str, Enum):
    """
    Enum representing the confidence level of a hypothesis.

    Attributes:
        SPECULATIVE: The hypothesis is based on weak or indirect evidence.
        PLAUSIBLE: The hypothesis is supported by some evidence but lacks robust validation.
        PROBABLE: The hypothesis is strongly supported by evidence and validation simulations.
    """

    SPECULATIVE = "SPECULATIVE"
    PLAUSIBLE = "PLAUSIBLE"
    PROBABLE = "PROBABLE"


class KnowledgeGapType(str, Enum):
    """
    Enum defining the type of knowledge gap identified.

    Attributes:
        CLUSTER_DISCONNECT: Disconnected clusters in the Knowledge Graph that should be connected.
        LITERATURE_INCONSISTENCY: Contradictions or inconsistencies found in scientific literature.
    """

    CLUSTER_DISCONNECT = "CLUSTER_DISCONNECT"
    LITERATURE_INCONSISTENCY = "LITERATURE_INCONSISTENCY"


class CritiqueSeverity(str, Enum):
    """
    Enum defining the severity of an adversarial critique.

    Attributes:
        LOW: Minor issues that do not significantly impact the hypothesis viability.
        MEDIUM: Issues that require attention or clarification but are not show-stoppers.
        HIGH: Significant risks (e.g., patent issues) that may require refinement.
        FATAL: Critical failures (e.g., toxicity) that reject the hypothesis.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    FATAL = "FATAL"


class Critique(BaseModel):
    """
    Represents a critique generated by an adversarial reviewer.

    Attributes:
        source: The source of the critique (e.g., "The Toxicologist").
        content: The textual content of the critique explaining the issue.
        severity: The severity level of the critique.
    """

    source: str
    content: str
    severity: CritiqueSeverity


class PICO(BaseModel):
    """
    Represents the PICO framework for experimental design.

    Attributes:
        population: The target population or biological system (e.g., "Mice with specific mutation").
        intervention: The experimental intervention (e.g., "Drug X administration").
        comparator: The control group or condition (e.g., "Placebo").
        outcome: The measured outcome or result (e.g., "Tumor size reduction").
    """

    population: str
    intervention: str
    comparator: str
    outcome: str


class GeneticTarget(BaseModel):
    """
    Represents a proposed genetic target for a hypothesis.

    Attributes:
        symbol: The gene symbol (e.g., "TP53").
        ensembl_id: The Ensembl ID for precise identification.
        druggability_score: A score indicating how suitable the target is for drug development.
        novelty_score: A score indicating the novelty of the target in this context.
    """

    symbol: str
    ensembl_id: str
    druggability_score: float  # From coreason-prism
    novelty_score: float


class KnowledgeGap(BaseModel):
    """
    Represents a identified gap in scientific knowledge.

    Attributes:
        id: Unique identifier for the gap.
        description: A textual description of the gap or inconsistency.
        type: The category of the knowledge gap.
        source_nodes: Optional list of graph nodes involved in the gap.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    description: str
    type: KnowledgeGapType
    source_nodes: Optional[List[str]] = None


class Hypothesis(BaseModel):
    """
    Represents a generated scientific hypothesis.

    Attributes:
        id: Unique identifier for the hypothesis.
        title: A concise title for the hypothesis.
        knowledge_gap: The problem statement or gap being addressed.
        proposed_mechanism: The proposed biological mechanism bridging the gap.
        target_candidate: The genetic target proposed by the hypothesis.
        causal_validation_score: Score from the causal simulation (0.0 - 1.0).
        key_counterfactual: Description of the key counterfactual scenario tested.
        killer_experiment_pico: The experimental design to validate the hypothesis.
        evidence_chain: List of citations or evidence nodes supporting the hypothesis.
        confidence: The confidence level of the hypothesis.
        critiques: List of critiques from the adversarial review process.
    """

    id: str
    title: str
    knowledge_gap: str  # The problem statement
    proposed_mechanism: str  # The biological pathway
    target_candidate: GeneticTarget

    # Validation
    causal_validation_score: float
    key_counterfactual: str

    # Experimental Design
    killer_experiment_pico: PICO

    # Provenance
    evidence_chain: List[str]  # Links to source papers/nodes
    confidence: ConfidenceLevel

    # Adversarial Review
    critiques: List[Critique] = Field(default_factory=list)


class BridgeResult(BaseModel):
    """
    Result from the BridgeBuilder component.

    Attributes:
        hypothesis: The generated hypothesis, if one was found.
        bridges_found_count: The number of potential bridges identified.
        considered_candidates: List of candidate symbols that were evaluated.
    """

    hypothesis: Optional[Hypothesis]
    bridges_found_count: int
    considered_candidates: List[str]  # Symbols of all candidates considered


class HypothesisTrace(BaseModel):
    """
    Complete audit trail for the hypothesis generation process.
    Captures the 'Why' and 'How' for scientific provenance.

    Attributes:
        hypothesis_id: Unique identifier of the generated hypothesis.
        gap_id: Identifier of the knowledge gap being addressed.
        bridge_id: Identifier of the bridge (target) used.
        gap: The KnowledgeGap object.
        bridges_found_count: Number of bridges found during the process.
        considered_candidates: List of candidates considered.
        excluded_targets_history: List of targets excluded during refinement.
        causal_validation_score: Score from the causal validation step.
        key_counterfactual: The counterfactual scenario tested.
        critiques: List of critiques received.
        refinement_retries: Number of refinement retries attempted.
        result: The final Hypothesis object, if successful.
        status: Status of the trace (e.g., "ACCEPTED", "DISCARDED", "PENDING", "ERROR").
    """

    hypothesis_id: Optional[str] = None
    gap_id: Optional[str] = None
    bridge_id: Optional[str] = None
    gap: KnowledgeGap

    # Bridge Phase
    bridges_found_count: int = 0
    considered_candidates: List[str] = Field(default_factory=list)
    excluded_targets_history: List[str] = Field(default_factory=list)

    # Simulation Phase
    causal_validation_score: Optional[float] = None
    key_counterfactual: Optional[str] = None

    # Critique Phase
    critiques: List[Critique] = Field(default_factory=list)
    refinement_retries: int = 0

    # Outcome
    result: Optional[Hypothesis] = None
    status: str = "PENDING"  # ACCEPTED, DISCARDED, REJECTED
